security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\Client:
            algorithm: bcrypt
    providers:
        entity_provider:
            entity:
                class: App\Entity\Client
                property: username
                # if you're using multiple entity managers
                # manager_name: customer
    firewalls:

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api_doc:
            pattern: ^/doc
            security: false
        refresh:
            pattern:  ^/token/refresh
            stateless: true
            anonymous: true
        api:
            pattern:   ^/
            stateless: true
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,      roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
