<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/vendor/composer/autoload_real.php';

passthru('php bin/console doctrine:database:drop --if-exists --force');
passthru('php bin/console doctrine:database:create');
passthru('php bin/console doctrine:schema:update --force');
passthru('php bin/console hautelook:fixtures:load -n');
return ComposerAutoloaderInit255042eac12b8cebc233eba1ecd4243c::getLoader();
