#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
    path:     /login_check
    methods:  [POST]

app.swagger_ui:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

gesdinet_jwt_refresh_token:
    path:     /token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }