product_1:
  model: "Galaxy Note 9"
  brand: "Samsung"
  description: "Le Galaxy Note 9 reprend dans les grandes lignes ce que Samsung proposait en début d’année avec le Galaxy S9+. Il en profite néanmoins pour corriger ses quelques lacunes et propose une meilleure ergonomie, une qualité photo supérieure et surtout l’intégration du S Pen, le fameux stylet de la marque qui est devenu Bluetooth sur cette génération afin de servir de télécommande. Beau, puissant, autonome, unique et excellent en photo… le Galaxy Note 9 frôle la perfection, à condition d’y mettre le prix bien sûr."
  color: "black"
  stock: "6"
  price: "930.00"

product_2:
  model: "Huawei P20 Pro"
  brand: "Huawei"
  description: "Le Huawei P20 Pro est le premier smartphone à disposer d’une configuration à triple capteur dorsal pour son appareil photo. Une configuration qui s’est faite remarquer pour la qualité des clichés qu’elle est capable d’offrir, particulièrement dans la nuit où les autres smartphones s’effacent très vite. Notre test du Huawei P20 Pro nous a également montré qu’il savait encaisser les tâches lourdes tout en offrant une excellente autonomie grâce à sa large batterie de 4000 mAh."
  color: "black"
  stock: "10"
  price: "661.00"

product_3:
  model: "Samsung Galaxy S9"
  brand: "Samsung"
  description: "Le Galaxy S9 impressionne dès le premier coup d’œil grâce à ses magnifiques finitions et son superbe écran AMOLED qui n’a rien à envier à ceux des autres smartphones. Il se distingue également grâce à ses performances boostées par le dernier SoC proposé par Samsung, l’Exynos 9810 et avec son très bon capteur photo dorsal qui peut s’ouvrir manuellement à f/1.5 ou f/2.4."
  color: "grey"
  stock: "23"
  price: "600.00"

product_4:
  model: "OnePlus 6"
  brand: "OnePlus"
  description: "Digne héritier d’une longue lignée de smartphone avec un rapport qualité/prix excellent, le OnePlus 6 a tout pour plaire. Il est sans aucun doute l’un des smartphones les plus performants de 2018 grâce à son SoC Snapdragon 845 et aux optimisations apportées par OxygenOS, l’interface maison de OnePlus qui se rapproche d’Android Pure. C’est une solution à étudier avant d’investir sur un smartphone plus cher."
  color: "black"
  stock: "38"
  price: "520.00"

product_5:
  model: "Xiaomi Mi 8"
  brand: "Xiaomi"
  description: "Le Xiaomi Mi 8, le dernier flagship de la marque chinoise, propose une expérience très complète sans gros défaut. Bon en photographie, équipé d’un superbe écran AMOLED, performant grâce à son SoC Snapdragon 845 le tout avec un design fin et élégant, Xiaomi livre l’une de ses plus belles réussites de 2018 avec le Mi 8."
  color: "black"
  stock: "33"
  price: "425.00"

product_6:
  model: "Xiaomi Mi Mix 2S"
  brand: "Xiaomi"
  description: "Le Xiaomi Mi Mix 2s transforme l’essai de la gamme Mix en réussite. Performant grâce à son SoC Qualcomm 845, autonome grâce à sa batterie de 3400 mAh et à ses optimisations logicielles efficaces, et proposant une excellente solution en photo (même s’il peine un peu en basse lumière), le Xiaomi Mi Mix 2s est l’un des meilleurs smartphones disponibles sur cette gamme de prix pour ceux qui ont envie d’avoir un écran sans encoche."
  color: "black"
  stock: "35"
  price: "400.00"

product_7:
  model: "Pocophone F1"
  brand: "Pocophone"
  description: "Le Pocophone F1 offre la puissance d’un Snapdragon 845 et une énorme autonomie. Il vaut donc clairement que l’on s’intéresse à lui. Toutefois, notons que pour proposer un tarif aussi séduisant, il a été obligé de faire quelques concessions. Sur son design notamment, puisqu’il ne revêt aucun matériau noble et se contente d’un dos en plastique, mais pour certains il ne s’agit pas d’un défaut puisque les rayures et la fragilité ne sont pas un problème. La qualité photo de l’appareil laisse également à désirer dans certaines conditions."
  color: "black"
  stock: "29"
  price: "314.99"

product_8:
  model: "Xiaomi Mi A2"
  brand: "Xiaomi"
  description: "Après le Mi A1 en 2017, Xiaomi réitère son partenariat avec Google en proposant un nouveau smartphone sous Android One : le Mi A2. Il propose donc une expérience épurée et simple, tout en affichant une fiche technique clairement au-dessus de ce qui se fait au même prix. Avec son Snapdragon 660 et ses 4 Go de RAM, c’est l’un des smartphones les plus performants de sa catégorie, mais il ne délaisse pas pour autant les autres points. Son écran de 5,99 pouces est très correct si l’on fait abstraction de ses problèmes de luminosité automatique et son appareil photo est de très bonne facture de jour. Dommage qu’il soit limité en basse lumière."
  color: "black"
  stock: "17"
  price: "208.00"

product_9:
  model: "Nokia 7 Plus"
  brand: "Nokia"
  description: "Au côté du Nokia 6.1 se tient le Nokia 7 Plus, version grand format de la même qualité de fabrication et la même volonté de rester sur l’expérience Android la plus pure possible avec le programme Android One. On passe cependant à un capteur photo plus performant et un grand écran de 6 pouces au ratio 18:9. Ici, l’appareil ne peut s’empêcher de rappeler un Google Pixel 2 XL en plus abordable. Pour toutes ces raisons, il est selon nous devenu le meilleur ambassadeur d’Android One."
  color: "black"
  stock: "349"
  price: "299.99"

product_10:
  model: "Huawei Mate 20 Lite"
  brand: "Huawei"
  description: "Le Huawei Mate 20 Lite se distingue essentiellement par son autonomie exemplaire qui permet de tenir plus d’une journée sans que le niveau de batterie ne soit vraiment inquiété. Ajoutez à cela une qualité photo correcte et un design très bien soigné et vous obtenez un smartphone qui se défend très bien sur sa gamme de prix. Côté caractéristiques, son Kirin 710 n’est bien sûr pas la meilleure puce du marché, mais elle fait tout de même bien le job."
  color: "black"
  stock: "88"
  price: "350.00"